### ISSUE TITLE
SignatureDoesNotMatch for manual request

### ISSUE THREAD

**Issue by x-wf** [apache/libcloud#1321]
## Summary
While attempting to perform a manual request, it appears to be an issue with the credentials being used.

## Detailed Information

Upon attempting to create EC2 Launch Template, by performing a manual request with the EC2 driver, it's returning `libcloud.common.types.InvalidCredsError: 'SignatureDoesNotMatch`

More specifically I have a function which I attempt to create a simple Launch Template
```
def initialize_test():

    # authenticate
    aws = get_driver(Provider.EC2)
    driver = login_aws(aws)

    // Other actions that are used e.g. driver.ex_create_security_group works perfect
    // Manually performing requests isn't working
    new_template(driver)
    
def new_template(driver):
    params = {
        'Action': 'CreateLaunchTemplate',
        'LaunchTemplateName': "test-template",
        'LaunchTemplateData': {
            'ImageId': "ami-06b41651a26fbba09",
            'InstanceType': "t3.xlarge",
            'NetworkInterface': {
                1: {
                    'AssociatePublicIpAddress': True
                }
            }
        }
    }

    // Breaks here
    response = driver.connection.request("/", params=params)
```

And this throws
```
libcloud.common.types.InvalidCredsError: 'SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.'
```
The project used is running python 3.7.4, using apache-libcloud 2.5.0.

**Comment by Kami** [comment]
Which signature algorithm you are using? I believe we default to v2.

I imagine it's something related to the nested dictionary you are trying to use - in EC2 driver we send data via query parameters and not as part of a request body.

This means you should use ``parent key.child key``` notation for your query param keys. So something like "params = {"LaunchTemplateData.ImageId: "...."}``. You can find an example of that here - https://github.com/apache/libcloud/pull/1224/files#diff-36825a12922cd525dde5f5dd9635f775R1887

If that doesn't work, I would add some debug / print statements to this method and see what is going on - https://github.com/apache/libcloud/blob/trunk/libcloud/common/aws.py#L205

And perhaps just try:

```python
    params = {
        'Action': 'CreateLaunchTemplate',
    }
```
 To see if that works (I believe it should and shouldn't throw signature mismatch error).

**Comment by Kami** [comment]
@x-wf^ did you have a chance yet to test it out?

**Comment by x-wf** [comment]
Hi @Kami ,

Thank you for getting back at me.
The solution was to exactly as you stated `"params = {"LaunchTemplateData.ImageId: "...."}"`. But errors like these could somehow be a bit more clear.

Once again, thank you.

**Comment by Kami** [comment]
I agree, we should throw in such scenario.

I will look into a code change for that.

**Comment by Kami** [comment]
#1329 should improve on this behavior.
