### ISSUE TITLE
Add function to remove a security group from a node in OpenStack driver

### ISSUE THREAD

**Issue by micafer** [apache/libcloud#1330]
## Add function to remove a security group from a node in OpenStack driver

Add function to remove a security group from a node. See the API info from:

https://docs.openstack.org/api-ref/compute/?expanded=remove-security-group-from-a-server-removesecuritygroup-action-detail#remove-security-group-from-a-server-removesecuritygroup-action

**Comment by Kami** [comment]
Resolved via #1331.
