### ISSUE TITLE
Add missing "cpuPlatform" field to GCE driver

### ISSUE THREAD

**Issue by yairshemla** [apache/libcloud#1342]
Add "cpuPlatform" and "minCpuPlatform" to GCE driver.
This field is already being fetched by libcloud, but gets discarded during the `_to_node` method.

on file `compute/drivers/gce.py`, line 8852 add:
`extra['cpuPlatform'] = node.get('cpuPlatform')`
`extra['minCpuPlatform'] = node.get('minCpuPlatform')`

**Comment by Kami** [comment]
@yairshemla Please feel free to open a pull request with this change - we are happy to merge it.

**Comment by yairshemla** [comment]
@Kami Hi, sure. here's the PR:
https://github.com/apache/libcloud/pull/1343

**Comment by Kami** [comment]
Resolved via #1343.
