### ISSUE TITLE
VCloud driver - why AdminPassword is removed from GuestCustomizationSection

### ISSUE THREAD

**Issue by KYDronePilot** [apache/libcloud#1352]
## Summary

There are 2 places in the VCloud driver code that remove the AdminPassword parameter from the GuestCustomizationSection of an API request due to an "API quirk", which I cannot find the origin of.

## Detailed Information

Version of libcloud: forked from commit a3334dc9, version 2.6.1-dev
Python version: 3.7.4
OS: Windows 10 1903

The error response I am getting from VCloud:
```xml
<ns0:Error majorErrorCode="400" message="[ xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx ] The administrator password cannot be empty when it is enabled and automatic password generation is not selected." minorErrorCode="BAD_REQUEST" xmlns:ns0="http://www.vmware.com/vcloud/v1.5"/>
```

More info on the GuestCustomizationSection can be found [here](https://www.vmware.com/support/vcd/doc/rest-api-doc-1.5-html/types/GuestCustomizationSectionType.html)

I am mainly interested in what the API quirk was that lead to this code being added. I am currently working on adding some new features to the libcloud driver and would be happy to implement any changes necessary if I have a better idea of what the problem is. From some quick digging around, it looks like the changes were added by **Michal Galet**.

**Comment by KYDronePilot** [comment]
I should also mention that the issue does not persist when commenting out the blocks of code that remove the AdminPassword parameter:

```python
# Remove AdminPassword from customization section
admin_pass = res.object.find(fixxpath(res.object, 'AdminPassword'))
if admin_pass is not None:
    res.object.remove(admin_pass)
```

```python
# Remove AdminPassword from customization section due to an API
# quirk
admin_pass = res.object.find(fixxpath(res.object, 'AdminPassword'))
if admin_pass is not None:
    res.object.remove(admin_pass)
```

**Comment by Kami** [comment]
I assume that's not an issue anymore now that #1373 has been merged?

**Comment by KYDronePilot** [comment]
Yes, that’s correct.
