### ISSUE TITLE
S3 get_driver using region name

### ISSUE THREAD

**Issue by maingoh** [apache/libcloud#1366]
For some reason it seems there is one driver for each S3 region.
Thus we cannot dynamically get a s3 driver depending on the region string.

For example something like this:
```
cls = get_driver(Provider.S3, region_name='eu-west-1')
``` 

Or maybe it would be better to have only one S3StorageDriver class where we can specify the region during construction.

```
driver = cls(access_key_id, secret_acces_key, region=region_name, region_name=region_name)
```

Though it seems there is two region attribute which should match. `region_name` from `S3StorageDriver` and `region` from `AWSDriver`.

**Comment by Kami** [comment]
The best approach would probably be to support ``region`` argument in the driver constructor.

That's something we already do in other drivers and similar to what you suggested in option 2).

**Comment by Kami** [comment]
@maingoh #1371 should resolve this issue.

It would be great if you can check / verify it if you get a chance.

**Comment by maingoh** [comment]
Great ! I will try :)

**Comment by maingoh** [comment]
It is working, just waiting for a new version :)

**Comment by Kami** [comment]
Thanks for confirming :)
