### ISSUE TITLE
Download page: issues with KEYS links and gpg verify

### ISSUE THREAD

**Issue by sebbASF** [apache/libcloud#1368]
The download page verification guide
https://libcloud.apache.org/downloads.html#package-verification-guide
has two references to the KEYS file; these should be links to 
https://www.apache.org/dist/libcloud/KEYS

[The initial mention of the KEYS file should ideally use just 'KEYS' as the link text, as that is how most other download pages present it]

==

Also the gpg verify commands should have a second parameter as follows:

gpg --verify apache-libcloud-2.3.0.tar.bz2.asc apache-libcloud-2.3.0.tar.bz2

See: https://www.apache.org/info/verification.html#specify_both

**Comment by Kami** [comment]
Fixed in https://svn.apache.org/viewvc?view=revision&revision=1869993.

Thanks for reporting this.

**Comment by sebbASF** [comment]
There is a second gpg command that needs adjusting under 'Example of a bad signature':

gpg --verify apache-libcloud-2.6.1.tar.bz2.asc
