### ISSUE TITLE
S3 Drivers issue.

### ISSUE THREAD

**Issue by 570096** [apache/libcloud#1379]
**## Summary**
Uploading a file into S3 . I am getting below error.

_ERROR:_
`**<LibcloudError in <class 'libcloud.storage.drivers.s3.S3StorageDriver'> 'This bucket is located in a different region. Please use the correct driver.'>**`

**## Detailed Information**
Version of libcloud:  2.6.1
Python version: 3.7
_**code:**_
```
`import libcloud
from libcloud.storage.types import Provider
from libcloud.storage.providers import get_driver
FILE_PATH = 'filepath' 
cls = get_driver(Provider.S3)
driver = cls('api key','api secret key')
container = driver.get_container(container_name='my-backups-12345')
extra = {'content_type': 'application/octet-stream'}
with open(FILE_PATH, 'rb') as iterator:
                obj = driver.upload_object_via_stream(iterator=iterator,
                                                      container=container,
                                                      object_name='images_backup.tar',
                                                      extra=extra)

```
In  the above code i mentioned correct driver then also am getting below error.please help me on this issue.Am I missing something?

![image](https://user-images.githubusercontent.com/41354386/70616592-d1165400-1c34-11ea-9f82-1aae5c287e3b.png)

**Comment by Kami** [comment]
@570096 I suggest you to install the latest stable version of Libcloud (v2.7.0) and then pass ``region=<region name>`` argument to the driver constructor and make sure the region matches the region where the bucket is located.

In v2.7.0, that exception has also been improved so the error now also includes the name of the region where the bucket in question is located.

For example, if your driver is located in the ``us-west-2`` region, you would instantiate a driver like this:

```python
cls = get_driver(Provider.S3)
driver = cls('api key','api secret key', region='us-west-2')
```

If you are working with buckets in different regions, you need to use multiple driver instances (one per region).

**Comment by JexPY** [comment]
@Kami If this answer will be in documentation there will be no questions. Thank you.
