### ISSUE TITLE
RuntimeError: dictionary keys changed during iteration

### ISSUE THREAD

**Issue by eamanu** [apache/libcloud#1382]
## Summary

During the packaging on Debian of libcloud a Runtime error happen [1]

[1] https://salsa.debian.org/python-team/modules/libcloud/-/jobs/452799

I think that I can send a patch  if you consider correct.

## Detailed Information

Debian unstable 
libcloud 2.5.0

**Comment by Kami** [comment]
Thanks for reporting this issue.

This has been fixed a while back (a01b074700ad0315009d98bfa36ac0969095377b) and was included in Libcloud v2.7.0 which was released on December 9, 2019.

I will close this issue. If it's still an issue with latest version of Libcloud, please re-open it.
