### ISSUE TITLE
AWS S3 Presigned URL and Azure Blob Storage Shared access signature

### ISSUE THREAD

**Issue by rvolykh** [apache/libcloud#1403]
## Feature Request

AWS S3 has the support of [Presigned Object URL](https://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURL.html) and Azure Blob Storage has the support of [Shared access signature](https://docs.microsoft.com/en-us/rest/api/storageservices/delegate-access-with-shared-access-signature).

Both of those features allow anyone (with whom shared link was shared) to download or upload a file. This feature is very useful when you want to temporary share a file with some user(s) or to allow them to upload a file, without sharing your credentials (temporary creds, creating an account, etc).

Currently, [libcloud Storage interface (API)](https://libcloud.readthedocs.io/en/stable/storage/api.html#storage-base-api) has two methods which more or less are related to sharing object access:
- [enable_object_cdn](https://libcloud.readthedocs.io/en/stable/storage/api.html#libcloud.storage.base.StorageDriver.enable_object_cdn) - Enable object CDN;
- [get_object_cdn_url](https://libcloud.readthedocs.io/en/stable/storage/api.html#libcloud.storage.base.StorageDriver.get_object_cdn_url) - Return an object CDN URL.

\* Both methods are not implemented either for AWS S3 nor Azure Blob Storage libcloud storage drivers.

My proposal is to extend `get_object_cdn_url` with additional parameter (mode=["read", "write"]) and implement support for AWS S3 and Azure Blob Storage.

**Comment by c-w** [comment]
Great suggestion. I'll take a stab at implementing the Azure Blob Storage part of this.

**Comment by Kami** [comment]
Resolved via #1408.
