### ISSUE TITLE
new driver: Kamatera

### ISSUE THREAD

**Issue by OriHoch** [apache/libcloud#1407]
Hi, I'm starting to develop a driver for [Kamatera](https://www.kamatera.com/)

Starting with the compute API.

Per the documentation: I'll use this issue as the umbrella place for all my changes and to ask questions.. (unless there is somewhere else I should do that)

**Comment by OriHoch** [comment]
Regarding `list_sizes` method of the compute API, currently [we](https://www.kamatera.com) allow for dynamic setting of machine size using arguments like cpu, ram, cpu type, disk size etc.. 

Is there any preference? I saw varying behaviors in other drivers:

* enumerate to predefined sizes
* not implement list_sizes method
* return a single size object and allow to set specific details in the create_node method

**Comment by Kami** [comment]
I think best approach would be to utilize option 1) in combination with allowing the user to specify a custom size by instantiating ``NodeImage`` class with custom values.

Here is an example of a driver which does that - https://libcloud.readthedocs.io/en/stable/compute/drivers/cloudsigma.html#create-a-server-using-a-custom-node-size

For custom attributes which are not supported by the ``NodeImage`` class you either have a choice of utilizing ``NodeImage`` class directly and putting custom attributes into ``extra`` directory or by subclassing it.

Utilizing ``NodeImage`` directly is preferred over custom sub-class (especially if other custom attributes are optional - this way it still works out of the box with "standard" NodeImage class instances).

----

EDIT: And where it makes sense and it's also applicable to other drivers / providers, we could perhaps also add some new standard attributes to the base / standard ``NodeImage`` class.

Things such as ``disk_type`` (hdd, ssd, etc.) come to mind.

Original ``NodeImage`` class implementation is quite old now and at that time providers didn't support things such as different disk types so it might make sense to extend it (and for backward compatibility reasons, we can default to ``hdd``).

**Comment by OriHoch** [comment]
that's very helpful, thanks @Kami

**Comment by Kami** [comment]
@OriHoch You are welcome.

Keep us posted :)

**Comment by OriHoch** [comment]
opened a PR: #1442
