### ISSUE TITLE
mypy issues as of 2.8.0

### ISSUE THREAD

**Issue by dpeschman** [apache/libcloud#1413]
## Summary
Just wanted to feed back to you all a couple issues we had running mypy on our custom drivers after upgrading to libcloud 2.8.0.

## Detailed Information
- The type of NodeDriver.type is Provider, but our custom drivers assign a string to this field which cause a mypy error.  Perhaps it should be Union[Provider, str]? 
- NodeSize, NodeLocation, and NodeImage have driver typed to be Type[NodeDriver] in their constructors, but this does not match Node, StorageVolume, and others which have it typed as NodeDriver.  We have subclasses of some of these and use self.driver as an instance of a driver, just like the Node class, and not as a driver class.

**Comment by dpeschman** [comment]
Forgot one more - what do you think about adding **kwargs back to create_node?

**Comment by Kami** [comment]
@dpeschman Thanks for reporting this issue, we will have a look.

As far as adding ``**kwargs`` goes - I don't think it should be part of the standard API. The whole point behind the standard API is so you know up front which arguments are available and supported.

Drivers can still use it, but even there explicitly declaring supported arguments is preferred and there are usually very few valid cases for using ``**kwargs`` (recent improvements related to that - #1389).

---

EDIT: On a related noted - do you have a specific / valid use case for ``**kwargs`` in mind?

**Comment by dpeschman** [comment]
Our use case is that our custom drivers take additional/other parameters to create_node that aren't in the base API.  But I see your point about using explicit keyword args and will update our drivers to do that and continue to ignore the mypy/lint arg mismatch in this case.
