### ISSUE TITLE
Issue in Create Volume

### ISSUE THREAD

**Issue by ngopi37** [apache/libcloud#1422]
## Summary

I tried creating new volume using below
driver.create_volume(size=volume_size,name=volume_name,location=None,snapshot=None) and am getting below error
MissingParameter: The request must contain the parameter zone

When i debug it expecting availability
/usr/local/lib/python3.7/dist-packages/libcloud/compute/drivers/ec2.py in create_volume

## Detailed Information

Am using Libcloud 2.8.0 and running on Python3.7 in Ubuntu 18TLS

Provide detailed information of your bug report.

This includes information about your environment (which Libcloud version are
you using, which Python version, which Operating System / distribution, etc.)
and steps which are needed to reproduce it.

For more information on contributing, please see https://libcloud.readthedocs.io/en/latest/development.html

**Comment by Kami** [comment]
I assume that's the EC2 driver.

If so, you also need to specify ``location`` argument.

---

It appears we need to update our code to make ``location`` argument mandatory (it appears ``AvailabilityZone`` parameter is now mandatory).

**Comment by Kami** [comment]
I pushed a change which will help with the default behavior (62c9c855f4fb8b409307cdc2f8358dda8f36f58a), but I would still recommend you to explicitly specify ``location`` argument.

**Comment by Kami** [comment]
Resolved via 62c9c855f4fb8b409307cdc2f8358dda8f36f58a.
