### ISSUE TITLE
GCE create_node() with location=None (default) throws AttributeError

### ISSUE THREAD

**Issue by kbknapp** [apache/libcloud#1441]
## Summary

Running with the GCE driver using `create_node(.. , location=None)` (which is a default) throws an `AttributeError`

## Detailed Information

OS: Ubuntu 19.10
libcloud Version: `apache-libcloud==2.8.1`
Python version: `Python 3.7.5`

Code to reproduce:

```python
gce = get_driver(Provider.GCE)(
            f'{user}@{project_id}.iam.gserviceaccount.com',
            api_key_file,
            project=project_id)

gce.create_node(name, size, None,
                             ex_network=network,
                             ex_subnetwork=subnet,
                             ex_tags=tags,
                             ex_metadata=metadata, 
                             external_ip='ephemeral',
                             internal_ip=internal_ip,
                             ex_image_family=image,
                             ex_disk_size=disk_sz)
```

With exception:

```
Traceback (most recent call last):
[ .. snip .. ]
  File "/home/kevin/.local/lib/python3.7/site-packages/proj/gcp/builder.py", line 181, in create_vm
    ex_disk_size=disk_sz)
  File "/home/kevin/.local/lib/python3.7/site-packages/libcloud/compute/drivers/gce.py", line 4169, in create_node
    location = self.ex_get_zone(location)
  File "/home/kevin/.local/lib/python3.7/site-packages/libcloud/compute/drivers/gce.py", line 7811, in ex_get_zone
    if name.startswith('https://'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by Kami** [comment]
Thanks for reporting this.

It's likely related to recent **kwargs refactoring. I will have a look.

**Comment by Kami** [comment]
I had a look and the issue is related to not passing ``datacenter`` argument to the driver constructor.

Location needs to be specified one way or another - either via constructor datacenter argument or via location argument to the create_node method.

**Comment by Kami** [comment]
Having said that - I will also open a PR so an exception is throw if neither of those is provided and clarify that in the docs.

Thanks again for reporting this.
