### ISSUE TITLE
URGENT: Broken link on download page

### ISSUE THREAD

**Issue by sebbASF** [apache/libcloud#1447]
The page
https://libcloud.apache.org/downloads.html

contains the link:

&lt;a href="https://www.apache.org/dist/libcloud/apache-libcloud-2.8.2.sha256">sha256</a&gt;

This does not work; it should be

&lt;a href="https://www.apache.org/dist/libcloud/apache-libcloud-2.8.2.zip.sha256">sha256</a&gt;

Please fix this urgently

**Comment by Kami** [comment]
This should now be fixed.

Thanks for reporting and sorry for the delay.
