### ISSUE TITLE
Pluggable authentication token cache for OpenStack driver

### ISSUE THREAD

**Issue by dpeschman** [apache/libcloud#1460]
## Feature Request

The OpenStack driver today caches Keystone authentication tokens in memory, allowing a single process to reuse a token for multiple requests.  In a system with many short-lived processes making calls, this cache does not provide its intended benefit.  A separate token is created for each process, and under load this can lead to a token flood in Keystone causing an outage.

We propose to make the token cache a parameter passed in at driver creation.  This object will adhere to an interface similar or identical to the one in use today for the in-memory cache, which will remain the default.  Users can pass in an alternative cache if the default does not suit their needs.

**Comment by Kami** [comment]
Resolved via #1557.
