### ISSUE TITLE
lockfile used for tests is deprecated

### ISSUE THREAD

**Issue by janko-j1** [apache/libcloud#1482]
See https://pypi.org/project/lockfile/. 

Please consider using fasteners or oslo.concurrency.

**Comment by michaelsembwever** [comment]
No just for tests.

You can't use local storage against a NFS window mount because of the use of this deprecated library.
https://github.com/apache/libcloud/blob/trunk/libcloud/storage/drivers/local.py#L56

**Comment by Kami** [comment]
``lockfile`` has been replaced with ``fasteners`` in latest trunk.

Do keep in mind that local storage driver was never really meant to be used for anything beyond testing.

**Comment by Kami** [comment]
Resolved via d110a45eb874bec8e3cf0b1371b515265293d6d9.
