### ISSUE TITLE
test_v4_signature_contains_credential_scope may fail if the time zone != UTC

### ISSUE THREAD

**Issue by yan12125** [apache/libcloud#1490]
## Summary

In `test_v4_signature_contains_credential_scope`, date in URL may not match the expected one if the time zone != UTC.

## Detailed Information

For example, I'm running on a machine with time zone CST (UTC+8). The aforementioned test fails
```
_ OSCRequestSignerAlgorithmV4TestCase.test_v4_signature_contains_credential_scope _
 
self = <libcloud.test.common.test_osc.OSCRequestSignerAlgorithmV4TestCase testMethod=test_v4_signature_contains_credential_scope>
 
    def test_v4_signature_contains_credential_scope(self):
        action = "ReadImages"
        headers = self.signer.get_request_headers(
            action=action,
            data="{}",
            service_name=self.driver.service_name,
            region=self.driver.region
        )
>       self.assertIn(
            'Credential=my_key/{}/my_region/my_service/osc4_request'.format(
                datetime.now().strftime('%Y%m%d')
            ),
            headers["Authorization"]
        )
E       AssertionError: 'Credential=my_key/20200921/my_region/my_service/osc4_request' not found in 'OSC4-HMAC-SHA256 Credential=my_key/20200920/my_region/my_service/osc4_request, SignedHeaders=content-type;host;x-osc-date, Signature=d0b6d1d916011b61a9963a0a61000a0e46253ab85b452596116ac410ed671561'
 
libcloud/test/common/test_osc.py:58: AssertionError
```

The build starts at 21 Sep 02:15:39 AM CST. The date is 20200921 in local time zone and 20200920 in UTC. Looks like the issue is that the test uses local time zone [1] while the code uses UTC [2]

[1] https://github.com/apache/libcloud/blob/1000049bb9955a071c78cb5f6f85ad6f4b780931/libcloud/test/common/test_osc.py#L60
[2] https://github.com/apache/libcloud/blob/1000049bb9955a071c78cb5f6f85ad6f4b780931/libcloud/common/osc.py#L77

Environment: Arch Linux, Python 3.8, apache-libcloud 3.2.0

**Comment by Aikoh0** [comment]
Hello @yan12125,
Thanks for pointing that out, I will look into it and come back to you as soon as possible,
Best regards

**Comment by Aikoh0** [comment]
Hi @yan12125,

Thanks again for reporting this, little mistake on me.
I have made a pull request which should fix this issue : https://github.com/apache/libcloud/pull/1493
Let me know if this still happens in the future.

Best regards !

**Comment by yan12125** [comment]
Thanks for the fast fix!
