### ISSUE TITLE
%m -> %M for minute

### ISSUE THREAD

**Issue by schwehr** [apache/libcloud#1500]
https://github.com/apache/libcloud/blob/trunk/libcloud/dns/base.py#L496

```
date = datetime.datetime.now().strftime('%Y-%m-%d %H:%m:%S')
```

should probably be

```
date = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
```

https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes

**Comment by Kami** [comment]
Thanks for the report. Fixed in 021c144e6e3e2aff04fff0f6dbb4e2a272ed6b41.
