### ISSUE TITLE
Change in behavior for S3 paths with leading slashes (/) between version 2.0.0 and 3.2.0

### ISSUE THREAD

**Issue by triplepoint** [apache/libcloud#1529]
## Summary

We're in the process of upgrading to the latest libcloud release (and Python 3) from a relatively old version 2.0.0 (and Python 2).  During testing, we discovered a change in behavior when uploading objects to AWS S3 when they had a double leading slash in the object path, after the bucket name, for example `s3://some-production-bucket//some-path/some-file.txt`.  Previously, this would've resulted in a folder-like object named `/` in the root of the path to the file, where now it does not, and `some-path` is the top-most folder-like object in the bucket.

While we realize this is bad practice, the leading object named `/` is valid by AWS S3's documentation, and for legacy reasons we cannot immediately migrate from this behavior.  We need to be able to access these double-leading-slash S3 paths as before.

## Detailed Information

In trying to trace this problem, I discovered this call path:
- `libcloud/storage/drivers/s3.py` : `upload_object()`
- `libcloud/storage/drivers/s3.py` : `self._put_object()` 
- `libcloud/storage/base.py`: `_upload_object()`  invokes `self.connection.request()`
- `libcloud/common/base.py`: `request()`
- `libcloud/common/base.py`: `self.morph_action_hook(action)`

It looks like the root of this behavior issue is in `morph_action_hook` on line 655, which attempts to strip out any double slashes:
```
    def morph_action_hook(self, action):
        url = urlparse.urljoin(self.request_path.lstrip('/').rstrip('/') +
                               '/', action.lstrip('/'))
        if not url.startswith('/'):
            return '/' + url
        else:
            return url
```
and its this that prevents our valid use of the top-level folder-like object named `/`.

I verified this by modifying `morph_action_hook()` to just `return action`, which works in our case because request_path is empty.  Uploading files with this change in place returns us to the previous behavior.  We've manually patched libcloud in our production deploy, but we'd very much like for that to be a temporary fix.

I don't entirely understand the goal of the current `morph_action_hook` implementation (except as maybe an attempt to protect users from their own mistakes?), but whatever it was, it was clearly added since our original application of this library at version 2.0.0.

Is there something I'm missing?  Is there a provision for disabling this corrective code that I'm not seeing?

Thanks in advance for any help you can give.

**Comment by Kami** [comment]
Thanks for reporting this.

I assume that change was done a long time ago during the migration to requests library and likely for compatibility reasons as you mentioned.

I do think we should support your use case as well, but that change would be backward incompatible / potentially breaking which means we need to use a feature flag or similar.

To begin with, perhaps just an argument which can be passed to the driver constructor. What do you think?

**Comment by Kami** [comment]
I believe this should work as a workaround - #1531.

As mentioned in that PR, sadly we can't make that a default behavior since it appears to break a lot of other things (it's also backward compatible) so we need to make it a "config option".

**Comment by triplepoint** [comment]
Thanks for getting to this so quickly, we appreciate it.  I did a quick review of the PR and it looks like it'll work fine for us, it's very similar to the patch we put in place.  I'll set up a test early next week to be sure.  Thanks again.

**Comment by Kami** [comment]
@triplepoint Did you happen to have a chance to test it yet?

I hope to work on a new release which will include this change in the next couple of days.

One thing worth pointing out is that setting module level variable to allow duplicate slashes will modify behavior for all the requests. So this could potentially cause issues if you are using multiple drivers.

One way to avoid that would be to add ``allow_duplicate_slashes`` argument to the S3 driver and then propagate this option all the way down to the connection class. This would require more glue code, but it would mean that change would only be scoped to that instance of the driver instead of globally.

WDYT?

**Comment by Kami** [comment]
For now I just updated upgrade notes and noted it affects all the instantiated drivers.

If it becomes an issue, we can introduce driver constructor argument which only applies to the driver in question,

**Comment by triplepoint** [comment]
Hi @Kami, I'm sorry, but with the holiday season we haven't gotten around to testing this yet.  I think we have a product release scheuled for mid january, and I intend to have this tested as a replacement for our internal patch for that release.  I'll report back here how it goes, but looking at the change, I think it'll work fine for us.   Thanks again.
