### ISSUE TITLE
Bad request, region is wrong for s3 minio

### ISSUE THREAD

**Issue by DrissiReda** [apache/libcloud#1539]
I'm trying to use minio driver with medusa (cassandra backup) and I'm getting error bad request: Here is the response:

```
{'connection': <libcloud.storage.drivers.minio.MinIOConnectionAWS4 object at 0x7f4d6f0e3be0>, 'headers': {'accept-ranges': 
'bytes', 'content-length': '583', 'content-security-policy': 'block-all-mixed-content', 'content-type': 'application/xml', 'server': 
'MinIO/RELEASE.2020-09-26T03-44-56Z', 'vary': 'Origin', 'x-amz-bucket-region': 'us-east-1', 'x-amz-request-id': 
'16574A0C19BFA20A', 'x-xss-protection': '1; mode=block', 'date': 'Tue, 05 Jan 2021 08:53:27 GMT'}, 'error': 'Bad Request', 
'status': 400, 'request': , 'iter_content': >, 'body': '\nAuthorizationHeaderMalformedThe authorization header is malformed; the
region is wrong; expecting 'us-east-1'.k8ssandra-dc1-default-sts-0.k8ssandra-dc1-service.kast.svc.cluster.local/test-dc1/meta
/schema.cqlcass/cass/k8ssandra-dc1-default-sts-0.k8ssandra-dc1-service.kast.svc.cluster.local/test-dc1/meta/schema.cqlus-
east-116574A0C19BFA20A0876c2f6-f423-4570-aa08-86ca582835e0', 'object': }
```

You can see that the region header is 'us-east-1' and it says it's expecting us-east-1, I don't understand what's wrong or what header is required.

Does anyone have an idea what might be broken?

Using python library apache-libcloud  v3.3.0

Running medusa on kubernetes, using master version.

MinIO version: RELEASE.2020-09-26T03-44-56Z

**Comment by DrissiReda** [comment]
Solved it by setting https://github.com/apache/libcloud/blob/4370a7021c11c1c61afe6470d2baafc093bfa0dd/libcloud/storage/drivers/minio.py#L49 to 
`region_name = "us-east-1"`

Not sure if it's worth a PR

**Comment by Kami** [comment]
Thanks for reporting this.

I will have a look and try to reproduce this issue (for me, minio driver works out of the box, but could be something related to your configuration - e.g. multiple regions or similar).

**Comment by DrissiReda** [comment]
Normally minio shouldn't rely on regions, which is why it's "us-east-1" by default, it's the s3 drivers that raises the issue since it requires it.
