### ISSUE TITLE
pricing.json on s3 public access is forbidden

### ISSUE THREAD

**Issue by miraculixx** [apache/libcloud#1582]
## Summary

According to the [documentation](https://libcloud.readthedocs.io/en/stable/compute/pricing.html) pricing data can be retrieved from a public s3 bucket. However this bucket does not currently seem available without proper authentication & authorization.

## Detailed Information

The docs state this command to download daily updated pricing data. It currently yields a 403:

```
$ curl --head https://libcloud-pricing-data.s3.amazonaws.com/pricing.json
HTTP/1.1 403 Forbidden
x-amz-request-id: QX4D6DZQJBT9CHBH
x-amz-id-2: c59u6Ga1nmDDrN955wBzVsrCGGdcT5bHKSpDTymc3PAqfpwFgLl996fTj9MWWW2aomxV/PA+7Sk=
Content-Type: application/xml
Date: Fri, 21 May 2021 14:52:06 GMT
Server: AmazonS3
```

The same is true for the programmatic download

```
$ python
> from libcloud.pricing import download_pricing_file
> download_pricing_file()
...
BaseHTTPError: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>YCC1QTBZSR4S3Z58</RequestId><HostId>lvf2BEKb81ljorimInxMzhfmTIrEY+IgGb60mWHs9w+asA8RMzHg1PGcBKMX4Jwd+OmUehAquTY=</HostId></Error>
```

Environment: 
```
$ pip freeze | grep libcloud
apache-libcloud==3.3.1

$ uname -v
#146~16.04.1-Ubuntu SMP Tue Apr 13 09:27:15 UTC 2021
```

**Comment by Kami** [comment]
Thanks for reporting this.

This likely broke recently when adding integration tests for S3. I will look into permissions and fix them.

I will also add a check as part of the nightly publish job which will fail the job if we fail to download pricing file.

**Comment by Kami** [comment]
This should now be fixed. I also added a CI check in ea364c58cd954d6b076c4e30bb283f33381a1246.

**Comment by Kami** [comment]
Confirmed it's working (https://github.com/apache/libcloud/runs/2644266413?check_suite_focus=true). Thanks again for reporting this.
