### ISSUE TITLE
Integration tests are failing

### ISSUE THREAD

**Issue by micafer** [apache/libcloud#1613]
## Integration tests are failing

Integration tests are failing due to timeout (6h).
It starts failing 3 months ago:
https://github.com/apache/libcloud/actions/runs/1013619673

**Comment by Kami** [comment]
I'll try to have a look over this weekend.

Looks like tests also produce no output which may make it a bit hard to troubleshoot. In any case, it looks like we also need timeout directly in the tox / pytest level to avoid such long runs and CI based timeouts.

**Comment by Kami** [comment]
#1616 fixes this issue.

I will also work with @c-w and see if we should pin used Docker images to a specific tag or similar to avoid such failures in the future.

**Comment by Kami** [comment]
Resolved via #1616.
