### ISSUE TITLE
use unittest.mock instead of mock

### ISSUE THREAD

**Issue by pgajdos** [apache/libcloud#1684]
Could you please consider to use unittest.mock, as a fallback at least?

**Comment by Kami** [comment]
Can you please provide some reasoning on this feature request? ``mock`` is a tests only dependency so it shouldn't be a problem if we depend on it (since we already depend on other libraries for tests as well).

**Comment by pgajdos** [comment]
Yes, forgot to add:
https://fedoraproject.org/wiki/Changes/DeprecatePythonMock
https://trello.com/b/WsskhdXA/opensuse-python

You seem to not support Python 2 anymore and as far as I tested:
https://build.opensuse.org/package/show/home:pgajdos:python/python-apache-libcloud
the testsuite run is successful at least with python 3.6 and later (see [python-apache-libcloud-no-mock.patch](https://build.opensuse.org/package/view_file/home:pgajdos:python/python-apache-libcloud/python-apache-libcloud-no-mock.patch)).

The root of this is sake of simplicity, why not use built-in unittest.mock instead of another library. That is of course your choice and feel free to close this in case you feel it is better to stay with python-mock.

Thank you for consideration

**Comment by Kami** [comment]
Thanks for the additional context.

If it simplifies the packaging and we don't loose any functionality, I'm fine with replacing it with stdlib mock module.

Not sure how much it really simplifies the packaging though, since we still have a lot of other test dependencies.

**Comment by Kami** [comment]
#1691 should solve this. Thanks for reporting this.

**Comment by Kami** [comment]
@pgajdos On a somewhat related note, I see there are some other patches upstream (https://build.opensuse.org/package/view_file/home:pgajdos:python/python-apache-libcloud/ec2_create_node.patch?expand=1, https://build.opensuse.org/package/view_file/home:pgajdos:python/python-apache-libcloud/gce_image_projects.patch?expand=1, https://build.opensuse.org/package/view_file/home:pgajdos:python/python-apache-libcloud/skip-some-tests-for-older-paramiko-versions.patch?expand=1).

All of those patches seem reasonable and we would be happy to accept them upstream if they are contributed to the project.

P.S. Thank you for your contribution to the Fedora project (I have been Fedora desktop / workstation user myself for many years now).
