### ISSUE TITLE
Azure arm driver does not list all nodes

### ISSUE THREAD

**Issue by jan-mue** [apache/libcloud#1824]
## Summary

The Azure ARM driver only lists 50 nodes in a subscription.

## Detailed Information

The function `list_nodes()` of the Azure ARM driver only lists 50 nodes when the Azure Portal shows more than 50 VMs.

This is probably caused by missing pagination here:
https://github.com/apache/libcloud/blob/trunk/libcloud/compute/drivers/azure_arm.py#L474

According to the documentation, there should be a property `nextLink` in the response:
https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/list-all

Libcloud version: 3.6.1
Python version: 3.10
Operating system: Ubuntu 20.04

**Comment by Kami** [comment]
Resolved via #1850.
