### ISSUE TITLE
this python project is vulnerable to MITM as it fails to verify the ssl validity of the remote destination

### ISSUE THREAD

**Issue by d1b** [apache/libcloud#2]
this python project is vulnerable to MITM as it fails to verify the ssl validity of the remote destination.
urllib / urllib2, httplib.SHTTPConnection do not verify ssl at all by default.
from base.py 
class ConnectionKey(object):
"""
A Base Connection class to derive from.
"""
conn_classes = (httplib.HTTPConnection, httplib.HTTPSConnection)

....
def connect(self, host=None, port=None):
.....
connection = self.conn_classes[self.secure](host, port)

this request can be MITMed leading to the compromise of a users API key - where a secured https connection was requested, but can be MITM'ed.

**Comment by jcsalterego** [comment]
This has been resolved with https://issues.apache.org/jira/browse/LIBCLOUD-65

More information is available at http://wiki.apache.org/incubator/LibcloudSSL
